/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import com.inet.viewer.SwingReportViewer;
import com.inet.viewer.URLRenderData;
import java.awt.BorderLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nanda
 */
public class Laporan_Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Laporan_Penjualan
     */
    public Laporan_Penjualan() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdSemua = new javax.swing.JRadioButton();
        rdPerbulan = new javax.swing.JRadioButton();
        rdPertahun = new javax.swing.JRadioButton();
        cbPertahun = new javax.swing.JComboBox();
        cbBulan = new javax.swing.JComboBox();
        cbPerbulanTahun = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 300, 100, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(690, 300, 100, 50);

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN PENJUALAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 810, 60);

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOKO DAYA FAMILY");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 60, 810, 40);

        buttonGroup1.add(rdSemua);
        rdSemua.setText("Semua");
        rdSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSemuaActionPerformed(evt);
            }
        });
        jPanel1.add(rdSemua);
        rdSemua.setBounds(30, 293, 90, 30);

        buttonGroup1.add(rdPerbulan);
        rdPerbulan.setText("Perbulan");
        jPanel1.add(rdPerbulan);
        rdPerbulan.setBounds(30, 150, 90, 30);

        buttonGroup1.add(rdPertahun);
        rdPertahun.setText("Pertahun");
        jPanel1.add(rdPertahun);
        rdPertahun.setBounds(30, 220, 90, 30);

        cbPertahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Tahun-", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        jPanel1.add(cbPertahun);
        cbPertahun.setBounds(160, 220, 90, 30);

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Bulan-", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jPanel1.add(cbBulan);
        cbBulan.setBounds(160, 150, 90, 30);

        cbPerbulanTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Tahun-", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        cbPerbulanTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerbulanTahunActionPerformed(evt);
            }
        });
        jPanel1.add(cbPerbulanTahun);
        cbPerbulanTahun.setBounds(280, 150, 90, 30);

        jLabel3.setText("Tahun");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 200, 34, 14);

        jLabel5.setText("Bulan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 130, 34, 14);

        jLabel6.setText("Tahun");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 130, 34, 14);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logoNew.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(710, 0, 100, 100);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (rdSemua.isSelected()) {
            try {
                String url = "http://localhost/inventoryFIFO/laporanPenjualanSemua.php";
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            } catch (IOException ex) {
                Logger.getLogger(MenuPimpinan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(rdPertahun.isSelected()){
            String tahun = (String) cbPertahun.getSelectedItem();
            try {
                String url = "http://localhost/inventoryFIFO/laporanPenjualanPertahun.php?tahun="+tahun;
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            } catch (IOException ex) {
                Logger.getLogger(MenuPimpinan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            String tahun = (String) cbPerbulanTahun.getSelectedItem();
            String bulan = (String) cbBulan.getSelectedItem();
            
            try {
                String url = "http://localhost/inventoryFIFO/laporanPenjualanPerbulan.php?tahun="+tahun+"&bulan="+bulan;
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
            } catch (IOException ex) {
                Logger.getLogger(MenuPimpinan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuPimpinan().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rdSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSemuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSemuaActionPerformed

    private void cbPerbulanTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerbulanTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPerbulanTahunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan_Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbBulan;
    private javax.swing.JComboBox cbPerbulanTahun;
    private javax.swing.JComboBox cbPertahun;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdPerbulan;
    private javax.swing.JRadioButton rdPertahun;
    private javax.swing.JRadioButton rdSemua;
    // End of variables declaration//GEN-END:variables
}
