/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atom;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanda
 */
public class Suplier extends javax.swing.JFrame {

    private Connection con;
    private ResultSet rs;
    private PreparedStatement ps;
    private Statement st;
    private DefaultTableModel dtm;
    private String sql;

    /**
     * Creates new form suplier
     */
    public Suplier() {
        initComponents();
        Koneksi koneksi = new Koneksi();
        con = koneksi.getKoneksi();
        try {
            st = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        bersih();
        cibuak();
    }

    private void bersih() {
//        throw new UnsupportedOperationException("Not yet implemented");
        txKodeSuplier.setText("");
        txNamaSuplier.setText("");
        txNohp.setText("");
        txAlamat.setText("");
        txKodeSuplier.requestFocus();
        txKodeSuplier.setEditable(true);
    }

    private void cibuak() {
        try {
            Object[] rows = {"KODE", " NAMA", "ALAMAT", "NO HP"};
            dtm = new DefaultTableModel(null, rows);
            tabelSuplier.setModel(dtm);
            tabelSuplier.setBorder(null);
            jScrollPane3.setVisible(true);
            jScrollPane3.setViewportView(tabelSuplier);
            String kd_suplier = "", nm_suplier = "", alamat = "", telp = "";
            try {
                sql = "select * from suplier ORDER BY kd_sup ASC";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    kd_suplier = rs.getString("kd_sup");
                    nm_suplier = rs.getString("nm_sup");
                    alamat = rs.getString("alamat");
                    telp = rs.getString("no_hp");
                    String[] tampil = {kd_suplier, nm_suplier, alamat, telp};
                    dtm.addRow(tampil);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Query Salah" + e.getMessage());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelSuplier = new javax.swing.JTable();
        txKodeSuplier = new javax.swing.JTextField();
        txNamaSuplier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAlamat = new javax.swing.JTextArea();
        txNohp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 1030, -1));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel1.setText("INPUT DATA SUPLIER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 420, 50));

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, 50));

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 50));

        jButton3.setBackground(new java.awt.Color(102, 102, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 130, 50));

        jButton4.setBackground(new java.awt.Color(102, 102, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 120, 50));

        tabelSuplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelSuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSuplierMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelSuplier);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 620, 90));

        txKodeSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKodeSuplierActionPerformed(evt);
            }
        });
        jPanel1.add(txKodeSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, 30));
        jPanel1.add(txNamaSuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 30));

        txAlamat.setColumns(20);
        txAlamat.setRows(5);
        jScrollPane1.setViewportView(txAlamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 170, 60));
        jPanel1.add(txNohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 170, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Kode Suplier");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Nama Suplier");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Alamat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("No. HP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 40, 2560, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            sql = "insert into suplier values('" + txKodeSuplier.getText()
                    + "','" + txNamaSuplier.getText()
                    + "','" + txAlamat.getText()
                    + "','" + txNohp.getText()
                    + "')";
            st = con.createStatement();
            st.executeUpdate(sql);
            bersih();
            cibuak();

            JOptionPane.showMessageDialog(null, "SUKSES TERSIMPAN");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "GAGAL TERSIMPAN" + e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (txKodeSuplier.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pilih salah satu data pada tabel");
            } else {
                sql = "update suplier set nm_sup='" + txNamaSuplier.getText()
                        + "',alamat='" + txAlamat.getText()
                        + "',no_hp='" + txNohp.getText()
                        + "' where kd_sup='" + txKodeSuplier.getText() + "'";
                st = con.createStatement();
                st.execute(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil Di EDIT");
                bersih();
                cibuak();
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txKodeSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKodeSuplierActionPerformed
        // TODO add your handling code here:
//        try {
//            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
//            con = DriverManager.getConnection("jdbc:odbc:pklpelet", "", "");
//            st = con.createStatement();
//            String sql = "select * from suplier where kd_suplier like '" + txKodeSuplier.getText() + "'";
//            ResultSet rs = st.executeQuery(sql);
//            if (rs.next()) {
//                txKodeSuplier.setText(rs.getString(1));
//                txNamaSuplier.setText(rs.getString(2));
//                txAlamat.setText(rs.getString(3));
//                txNohp.setText(rs.getString(4));
//            } else {
//                JOptionPane.showMessageDialog(null, "Tidak ada data");
//
//            }
//            st.close();
//            con.close();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
//        }
    }//GEN-LAST:event_txKodeSuplierActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Menu().setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (txKodeSuplier.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Pilih salah satu data pada tabel");
            } else {
                sql = "DELETE from suplier where kd_sup='" + txKodeSuplier.getText() + "'";
                st = con.createStatement();
                st.execute(sql);
                JOptionPane.showMessageDialog(null, "Data Telah Dihapus!!");
                bersih();
                cibuak();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelSuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSuplierMouseClicked
        // TODO add your handling code here:
         txKodeSuplier.setText(dtm.getValueAt(tabelSuplier.getSelectedRow(), 0) + "");
        txNamaSuplier.setText(dtm.getValueAt(tabelSuplier.getSelectedRow(), 1) + "");
        txAlamat.setText(dtm.getValueAt(tabelSuplier.getSelectedRow(), 2) + "");
        txNohp.setText(dtm.getValueAt(tabelSuplier.getSelectedRow(), 3) + "");
        txKodeSuplier.setEditable(false);
    }//GEN-LAST:event_tabelSuplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suplier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelSuplier;
    private javax.swing.JTextArea txAlamat;
    private javax.swing.JTextField txKodeSuplier;
    private javax.swing.JTextField txNamaSuplier;
    private javax.swing.JTextField txNohp;
    // End of variables declaration//GEN-END:variables
}
